### ISSUE TITLE
license for this repository is missing

### ISSUE THREAD

**Issue by melutovich** [neuroforgede/docker-swarm-repository-layout#2]
This repository itself does not have that I can see a license, what is the license for it?

**Comment by s4ke** [comment]
Actually I didn't think about that. It should be MIT licensed, but we didn't add a license file yet.

**Comment by melutovich** [comment]
Ok, I'll keep a look out for it.

**Comment by s4ke** [comment]
Added a LICENSE file

**Comment by melutovich** [comment]
Thanks!
